on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

name: PR CI Workflow
jobs:
  ci-go:
    name: CI Test Go
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [1.18.2]
    steps:
      - name: Checkout 
        uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - run: go mod download
      - run: make test
